name: Github Rebot for Sealos
on:
  issue_comment:
    types:
      - created
env:
  GH_TOKEN: "${{ secrets.GH_PAT }}"
jobs:
  comment:
    if: startswith(github.event.comment.body, '/release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Gh Rebot for Sealos
        uses: labring/robot@v0.0.6
        with:
          version: v0.0.6
        env:
          SEALOS_TYPE: "/comment"
          GH_TOKEN: "${{ secrets.GH_PAT }}"
