name: Github Rebot for Sealos test PR

on:
  - push
  - pull_request_target

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build file
        run: |
          make install
      - if: ${{ (github.event_name != 'push') }}
        run: |
          robot action
        env:
          SEALOS_TYPE: "issue_comment"
          SEALOS_FILENAME: "templates/template.md"
          SEALOS_REPLACE_TAG: "DEFAULT"
          GH_TOKEN: "${{ secrets.GH_PAT }}"
      - name: add file
        run: |
          echo "somethings.....default" >> templates/template.md
      - if: ${{ (github.event_name != 'push') }}
        run: |
          robot action
        env:
          SEALOS_TYPE: "issue_comment"
          SEALOS_FILENAME: "templates/template.md"
          SEALOS_REPLACE_TAG: "DEFAULT"
          GH_TOKEN: "${{ secrets.GH_PAT }}"
